export const REGISTER_SUCCESS = "REGISTER_SUCCESS"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const REGISTER_FAIL = "REGISTER_FAIL"
export const LOGIN_FAIL = "LOGIN_FAIL"
export const AUTH_ERROR = "AUTH_ERROR"
export const LOGOUT = "LOGOUT"

export const GET_PROFILES = "GET_PROFILES"
export const PROFILE_ERROR = "PROFILE_ERROR"
export const SAVE_PROFILES = "SAVE_PROFILES"

export const RESULTS = "RESULTS"
